"""initial schema

Revision ID: 5232e1b7cffe
Revises: 
Create Date: 2026-03-01 16:05:21.046639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5232e1b7cffe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgcrypto for gen_random_uuid()
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('claude_api_key_enc', sa.Text(), nullable=True, comment='AES-256 encrypted BYOK Claude API key'),
    sa.Column('nanobanana_api_key_enc', sa.Text(), nullable=True, comment='AES-256 encrypted BYOK Nanobanana API key'),
    sa.Column('default_color_scheme', sa.String(length=50), nullable=False),
    sa.Column('default_resolution', sa.String(length=10), nullable=False),
    sa.Column('default_aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('claude_tokens_quota', sa.Integer(), nullable=False),
    sa.Column('nanobanana_images_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('color_schemes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='null = system preset'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False, comment='preset/custom'),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Keys: primary, secondary, tertiary, text, fill, section_bg, border, arrow'),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('paper_field', sa.String(length=100), nullable=True, comment="e.g. 'computer vision', 'NLP'"),
    sa.Column('color_scheme', sa.String(length=50), nullable=False),
    sa.Column('custom_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active/archived/deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='pdf/docx/txt'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Parsed chapter structure'),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=False, comment='pending/parsing/completed/failed'),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_index('ix_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('api_name', sa.String(length=50), nullable=False, comment='claude/nanobanana'),
    sa.Column('api_endpoint', sa.String(length=200), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('claude_model', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=10), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=True),
    sa.Column('request_duration_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('billing_period', sa.String(length=7), nullable=False, comment='YYYY-MM format'),
    sa.Column('key_source', sa.String(length=20), nullable=False, comment='platform/byok'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_logs_user_billing', 'usage_logs', ['user_id', 'billing_period'], unique=False)
    op.create_index('ix_usage_logs_user_id', 'usage_logs', ['user_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('figure_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('original_prompt', sa.Text(), nullable=True, comment='Claude-generated prompt'),
    sa.Column('edited_prompt', sa.Text(), nullable=True, comment='User-edited prompt'),
    sa.Column('suggested_figure_type', sa.String(length=50), nullable=True),
    sa.Column('suggested_aspect_ratio', sa.String(length=10), nullable=True),
    sa.Column('source_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Which document sections this prompt covers'),
    sa.Column('claude_model', sa.String(length=50), nullable=True),
    sa.Column('generation_task_id', sa.String(length=100), nullable=True, comment='Celery task ID'),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompts_project_id', 'prompts', ['project_id'], unique=False)
    op.create_index('ix_prompts_user_id', 'prompts', ['user_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resolution', sa.String(length=10), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('color_scheme', sa.String(length=50), nullable=True),
    sa.Column('custom_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_image_path', sa.String(length=1000), nullable=True),
    sa.Column('edit_instruction', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('generation_task_id', sa.String(length=100), nullable=True, comment='Celery task ID'),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('generation_duration_ms', sa.Integer(), nullable=True),
    sa.Column('final_prompt_sent', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_images_project_id', 'images', ['project_id'], unique=False)
    op.create_index('ix_images_prompt_id', 'images', ['prompt_id'], unique=False)
    op.create_index('ix_images_user_id', 'images', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_user_id', table_name='images')
    op.drop_index('ix_images_prompt_id', table_name='images')
    op.drop_index('ix_images_project_id', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_prompts_user_id', table_name='prompts')
    op.drop_index('ix_prompts_project_id', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('ix_usage_logs_user_id', table_name='usage_logs')
    op.drop_index('ix_usage_logs_user_billing', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index('ix_documents_user_id', table_name='documents')
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_table('projects')
    op.drop_table('color_schemes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
