"""add_system_settings_and_user_api_urls

Revision ID: 5e5d8670cbfe
Revises: 5232e1b7cffe
Create Date: 2026-03-01 16:36:00.703277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5d8670cbfe'
down_revision: Union[str, Sequence[str], None] = '5232e1b7cffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claude_api_key_enc', sa.Text(), nullable=True, comment='AES-256 encrypted system Claude API key'),
    sa.Column('claude_api_base_url', sa.String(length=500), nullable=True, comment='Custom Claude API base URL (e.g. proxy)'),
    sa.Column('claude_model', sa.String(length=100), nullable=True, comment='Claude model override'),
    sa.Column('nanobanana_api_key_enc', sa.Text(), nullable=True, comment='AES-256 encrypted system NanoBanana API key'),
    sa.Column('nanobanana_api_base_url', sa.String(length=500), nullable=True, comment='Custom NanoBanana API base URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('claude_api_base_url', sa.String(length=500), nullable=True, comment='User-custom Claude API base URL'))
    op.add_column('users', sa.Column('nanobanana_api_base_url', sa.String(length=500), nullable=True, comment='User-custom NanoBanana API base URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nanobanana_api_base_url')
    op.drop_column('users', 'claude_api_base_url')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
